name: clpfus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/LOGO-2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/



